const Menu = [
  {
    id: 7,
    image: "images/omelette.jpg",
    name: "omelette",
    category: "breakfast",
    price: 25,
    description: "fluffy omelette made with farm-fresh eggs",
  },
  {
    id: 3,
    image: "images/salad.jpg",
    name: "salad",
    category: "lunch",
    price: 20,
    description: "fresh and healthy salad",
  },
  {
    id: 1,
    image: "images/maggi.jpg",
    name: "maggi",
    category: "evening snacks",
    price: 25,
    description: "2 minute Noodles",
  },
  {
    id: 6,
    image: "images/fries.jpg",
    name: "fries",
    category: "evening snacks",
    price: 15,
    description: "crispy and golden french fries",
  },
  {
    id: 2,
    image: "images/pizza.jpg",
    name: "pizza",
    category: "dinner",
    price: 50,
    description: "delicious pizza with various toppings",
  },
  {
    id: 4,
    image: "images/sandwich.jpg",
    name: "sandwich",
    category: "lunch",
    price: 30,
    description: "a tasty sandwich with your choice of fillings",
  },
  {
    id: 5,
    image: "images/burger.jpg",
    name: "burger",
    category: "dinner",
    price: 40,
    description: "juicy burger with all the fixings",
  },
  {
    id: 8,
    image: "images/pancakes.jpg",
    name: "pancakes",
    category: "breakfast",
    price: 30,
    description: "stack of fluffy pancakes served with maple syrup",
  },
  {
    id: 9,
    image: "images/tea.jpg",
    name: "tea",
    category: "evening snacks",
    price: 10,
    description: "refreshing cup of tea to rejuvenate your evening",
  },
];

export default Menu;